#!/usr/bin/env python3
"""results/summary.md from results/*.json.   python scripts/summarize.py [results]"""
import json
import os
import sys

import numpy as np
import pandas as pd

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
R = sys.argv[1] if len(sys.argv) > 1 else os.path.join(ROOT, "results")
out = []


def load(name):
    p = os.path.join(R, name)
    return json.load(open(p, encoding="utf-8")) if os.path.exists(p) else None


def P(s=""):
    out.append(s)


def table(cols, rows):
    P("| " + " | ".join(cols) + " |"); P("|" + "---|" * len(cols))
    for r in rows:
        P("| " + " | ".join(str(c) for c in r) + " |")
    P()


def f0(x):
    return "-" if x is None else f"{x:.0f}"


P("# Results summary\n")
P("Generated by scripts/summarize.py from results/*.json.\n")

run = load("run.json")
if run:
    days = run["days"]; fd = [d for d in days if d["fault_day"]]; cd = [d for d in days if not d["fault_day"]]
    P(f"## The run: {run['from']} to {run['to']}, {len(days)} trading days ({len(fd)} with injected faults, {len(cd)} clean), AUM ${run['config']['aum'] / 1e9:.0f}bn, brokers {', '.join(run['config']['brokers'])}\n")
    P(f"Orders {sum(d['orders'] for d in days):,} ({np.mean([d['orders'] for d in days]):.0f} per day), fills booked {sum(d['fills'] for d in days):,}, drop-copy fills {sum(d['dropcopy_fills'] for d in days):,}; gross strategy deltas ${sum(d['netting']['gross'] for d in days) / 1e9:.1f}bn of which ${sum(d['netting']['crossed'] for d in days) / 1e9:.2f}bn crossed internally and ${sum(d['netting']['net'] for d in days) / 1e9:.1f}bn sent; corporate actions applied on {sum(d['ca_applied'] for d in days)} position lines; runtime {run['runtime_s'] / 60:.0f} minutes.\n")
    table(["date", "kind", "orders", "fills", "alert incidents", "faults caught", "recon seeded found", "unexplained breaks", "checks warn/fail"],
          [[d["date"], "fault" if d["fault_day"] else "clean", d["orders"], d["fills"], d["incidents"], f"{d['faults_detected']}/{d['faults_injected']}" if d["fault_day"] else "-", f"{d['recon']['found']}/{d['recon']['seeded']}", d["recon"]["unexplained"], f"{d['checks_warn']}/{d['checks_fail']}"] for d in days])

m = load("monitor.json")
if m:
    P("## Live monitor: fault injection\n")
    P(f"Over the {m['fault_days']} fault days {m['injected']} faults were injected into the brokers and the transport; the monitor caught {m['detected']} ({100 * m['detection_rate']:.0f} %) with a median time to detect of {m['median_ttd_s']:.0f} s (p90 {m['p90_ttd_s']:.0f} s). The two that are not the monitor's job (`dropcopy_missing`) are found by the end-of-day reconciliation. On the {m['clean_days']} clean days the monitor raised {m['false_alerts_per_clean_day']:.1f} alerts per day ({m['clean_incidents_per_day']:.1f} incidents).\n")
    table(["fault", "injected", "detected", "median time to detect (s)", "p90 (s)", "what the monitor sees"],
          [[t, v["injected"], v["detected"], f0(v["median_ttd_s"]), f0(v["p90_ttd_s"]), {"drop_ack": "UNACKED", "stuck": "STALLED / BEHIND_SCHEDULE / LEAVES_AFTER_END", "dup_fill": "STATE_ANOMALY duplicate ExecID", "bad_price": "PRICE_COLLAR", "over_participation": "PARTICIPATION / AHEAD_SCHEDULE", "wrong_side": "STATE_ANOMALY side", "symbol_mismatch": "STATE_ANOMALY symbol", "late_fill_after_cancel": "STATE_ANOMALY fill after Canceled", "reject_storm": "REJECT_RATE", "stale_leaves": "STATE_ANOMALY LeavesQty", "overfill": "STATE_ANOMALY overfill", "silent_session": "SESSION_SILENT / SESSION_LOST", "seq_gap": "SEQ_GAP", "latency_spike": "LATENCY", "dropcopy_missing": "(EOD reconciliation)"}.get(t, "")] for t, v in m["by_type"].items()])
    if m.get("false_alerts_by_rule"):
        P("Alerts on clean days by rule: " + ", ".join(f"{k} {v}" for k, v in m["false_alerts_by_rule"].items()) + ".\n")

rc = load("recon.json")
if rc:
    P("## End-of-day reconciliation\n")
    P(f"{rc['fills_reconciled']:,} internal fills reconciled against the drop copy and the prime broker file over {rc['days']} days. Seeded breaks: {rc['found']} of {rc['seeded']} found and classified; {rc['unexplained']} breaks unexplained (a clean day reconciles to zero).\n")
    table(["break type", "seeded", "found"], [[t, v["seeded"], v["found"]] for t, v in rc["by_type"].items()])
    lab = pd.DataFrame(rc["breaks_by_type_and_label"])
    if len(lab):
        P("Every break raised over the run, by type and label (label = the seeded break it matched, the fault or rejected report that explains it, `late_booking` / `late_booking_resolved` for the two-day pair, or blank when unexplained):\n")
        table(["break type", "label", "n"], lab.values.tolist())

t = load("tca.json")
if t:
    s = t["summary"]
    P("## Transaction cost analysis\n")
    P(f"{s['n_orders']:,} executed orders, ${s['notional_usd'] / 1e9:.1f}bn. Implementation shortfall {s['is_bp']:.1f} bp of the decision price = delay {s['is_delay_bp']:.1f} + execution {s['is_execution_bp']:.1f} + opportunity {s['is_opportunity_bp']:.1f} + fees {s['is_fees_bp']:.1f} (Perold; exact by construction). Execution vs arrival {s['execution_bp']:.1f} bp, vs interval VWAP {s['vwap_bp']:.1f} bp, fill rate {100 * s['fill_rate']:.0f} %.\n")
    table(["algo", "orders", "cost vs its benchmark (bp)", "vs arrival (bp)", "vs VWAP (bp)", "fill rate"], [[a, v["n"], f"{v['benchmark_bp']:.1f}", f"{v['execution_bp']:.1f}", f"{v['vwap_bp']:.1f}", f"{100 * v['fill_rate']:.0f} %"] for a, v in s["by_algo"].items()])
    table(["difficulty (0 <1% ADV, 1 1-5%, 2 >5%)", "orders", "vs arrival (bp)", "vs VWAP (bp)", "pre-trade estimate (bp)"], [[k, v["n"], f"{v['execution_bp']:.1f}", f"{v['vwap_bp']:.1f}", f"{v['pretrade_bp']:.1f}"] for k, v in s["by_difficulty"].items()])
    w = t["wheel"]
    if "brokers" in w:
        P(f"### Broker wheel ({w['n']} schedule-algo orders: VWAP and POV against the interval VWAP, close orders against the close; cost regressed on sqrt(%ADV) x volatility, spread, algo, urgency and region with broker fixed effects; residual sd {w['residual_sd_bp']:.0f} bp)\n")
        b0 = list(w["brokers"])[0]
        table(["broker", "orders", "raw cost vs benchmark (bp)", f"effect vs {b0} (bp)", "95 % CI", "P(best)", "by algo (bp)"], [[b, v["n_orders"], f"{v['raw_cost_bp']:.1f}", f"{v[[k for k in v if k.startswith('effect')][0]]:+.1f}", f"[{v['ci95'][0]:+.1f}, {v['ci95'][1]:+.1f}]", f"{v['p_best']:.2f}", ", ".join(f"{a} {x:.1f}" for a, x in v["by_algo_bp"].items())] for b, v in w["brokers"].items()])
        P("Orders per broker needed to resolve a difference at 80 % power: " + ", ".join(f"{k}: {v:,}" for k, v in w["power"].items()) + f". Ranking by estimated effect: {' < '.join(w['ranking'])}; the simulator's true quality order is BRK1 < BRK2 < BRK3 (impact multipliers 0.85, 1.00, 1.25).\n")
        wa = w.get("all_orders_vs_vwap")
        if wa and "brokers" in wa:
            P(f"On all {wa['n']} orders including the implementation-shortfall ones measured against the interval VWAP (residual sd {wa['residual_sd_bp']:.0f} bp) the effects are " + ", ".join(f"{b} {v[[k for k in v if k.startswith('effect')][0]]:+.1f} [{v['ci95'][0]:+.1f}, {v['ci95'][1]:+.1f}]" for b, v in wa["brokers"].items()) + f"; resolving 2 bp would take {wa['power']['2.0bp']:,} orders per broker. The benchmark has to fit the algo before a wheel can rank anyone.\n")
    p = t["pretrade"]
    if "coefficients" in p:
        P(f"Pre-trade model on the schedule-algo orders: cost = {p['coefficients']['const_bp']:.1f} + {p['coefficients']['impact']:.2f} x sigma_bp x sqrt(Q/ADV) + {p['coefficients']['spread']:.2f} x spread_bp, fitted on {p['n_train']} orders before {p['cut_date'][:10]}, tested on {p['n_test']}: RMSE {p['test_rmse_bp']:.1f} bp against {p['naive_rmse_bp']:.1f} for the training mean, out-of-sample correlation {p['test_corr']:.2f}.\n")

c = load("corpact.json")
if c:
    P("## Corporate actions\n")
    ar, fx = c["as_reported"], c["lse_dividends_in_pounds"]
    P(f"Feed: " + ", ".join(f"{k} {v:,}" for k, v in c["events_in_feed"].items()) + f". Dividend factors checked against Yahoo's adjusted close: {c['dividends_checked']:,} events; as reported {ar['within_tol']:,} within 5e-4 (median relative error {ar['median_rel_err']:.1e}); with LSE dividends read in pounds {fx['within_tol']:,} within tolerance (median {fx['median_rel_err']:.1e}, max {fx['max_rel_err']:.1e}); {fx['unexplained_adjustments']} adjustment days without an event in the feed.\n")
    table(["exchange", "dividends", "within tol, as reported", "median error, as reported", "within tol, LSE in pounds", "median error, LSE in pounds"], [[k, v["n"], v["within_tol"], f"{v['median']:.1e}", fx["by_exchange"][k]["within_tol"], f"{fx['by_exchange'][k]['median']:.1e}"] for k, v in ar["by_exchange"].items()])
    P(c["note"] + "\n")

cal = load("calendar_check.json")
if cal:
    P("## Exchange calendars vs the trading days in the data\n")
    table(["exchange", "symbols", "period", "calendar days", "data days", "calendar open but no data", "data on a calendar-closed day"], [[k, v["symbols"], f"{v['from']}..{v['to']}", v["calendar_days"], v["data_days"], ", ".join(v["calendar_open_but_no_data"]) or "-", ", ".join(v["data_on_calendar_closed"]) or "-"] for k, v in cal.items()])

fi = load("fi_check.json")
if fi:
    P("## Fixed-income and derivatives calendars\n")
    table(["contract", "first notice", "last trade"], [[k, v.get("first_notice") or "-", v["last_trade"]] for k, v in fi["futures"].items()])
    P("Front contracts today: " + ", ".join(f"{k} {v}" for k, v in fi["front_today"].items()) + f". CDX rolls {fi['cdx']['2026']}; monthly option expiries 2026: {', '.join(fi['options']['2026'])}. TBA (SIFMA) " + "; ".join(f"{k}: notification {v['notification']}, settlement {v['settlement']}" for k, v in list(fi["tba"].items())[:4]) + f". TIPS reference CPI today {fi['tips']['reference_cpi_today']:.3f} from {fi['tips']['months_of_cpi']} months of CPI-U.\n")

if run:
    P("## Checks\n")
    ck = pd.DataFrame(run["checks"])
    if len(ck):
        ck["name"] = [n.split(":")[0] for n in ck["check_name"]]; piv = ck.groupby(["phase", "name", "status"])["n"].sum().unstack(fill_value=0).reset_index()
        table(["phase", "check", "ok", "warn", "fail"], [[r["phase"], r["name"], r.get("ok", 0), r.get("warn", 0), r.get("fail", 0)] for _, r in piv.iterrows()])

open(os.path.join(R, "summary.md"), "w", encoding="utf-8").write("\n".join(out) + "\n")
print("wrote", os.path.join(R, "summary.md"), len(out), "lines")
